### ISSUE TITLE
0.15.4 bug and not working transfer

### ISSUE THREAD

**Issue by MrGenga** [iTXTech/SynapseAPI#11]
There is not loaded chunks, but tile entities(signs) I see. Interact don't work. And when I trying to transfer, there is no working, I get null instead hash, but server with that description is connected to Nemisys.

**Comment by MrGenga** [comment]
@PeratX @boybook help!

**Comment by File14** [comment]
Same issuse!

**Comment by File14** [comment]
Fixed, close the issuse @MrGe
