### ISSUE TITLE
synapse disconnects from nemisys.....

### ISSUE THREAD

**Issue by Creeperface01** [iTXTech/SynapseAPI#19]
And this happens very often... ussually on join... so i can not start my server because this kicks all players..... @boybook @PeratX 

or if you know how to fix this issue

> 22:50:18 [NOTICE] [SynapseAPI] Synapse Client has disconnected due to timeout
> 
> 22:50:18 [INFO] CreeperFace[/193.165.24.1:19132] logged out due to Server Closed
> 
> 22:50:18 [NOTICE] Trying to re-connect to Synapse Server
> 
> 22:50:18 [NOTICE] SynapseAPI has connected to e.gameteam.cz:10305
> 
> 22:50:18 [NOTICE] [SynapseAPI] Connecting e.gameteam.cz:10305
> 
> 22:50:18 [NOTICE] [SynapseAPI] Login success to e.gameteam.cz:10305

**Comment by boybook** [comment]
This looks like your Nukkit's main thread lag.

**Comment by Creeperface01** [comment]
No, i tested it and its nemisys main thread lag

**Comment by Creeperface01** [comment]
And happens only if you run nukkit and nemisys on different IPs

**Comment by boybook** [comment]
I'm founding the reason of the packet loss.
And I might find some reason to try to fix it.

**Comment by boybook** [comment]
I have some suggestions about this. To reduce the data transmission speed and the amount of data sent. And please make the connection to be reliable and stable, try not to trigger TCP packet loss and packet loss retransmission mechanism.

**Comment by Creeperface01** [comment]
Cool :) I hope it could be fixed because now i must run all my servers with the same IP (same machine)
