### ISSUE TITLE
Download the plugin?

### ISSUE THREAD

**Issue by File14** [iTXTech/SynapseAPI#2]
Where can I download the jar file? Can I have a link?

**Comment by File14** [comment]
@PeratX

**Comment by ishitatsuyuki** [comment]
No spam pinging. Build it yourself.

**Comment by File14** [comment]
I'm not "spam pinging", I just tagged them to ask a question... @ishitatsuyuki

**Comment by ishitatsuyuki** [comment]
Remember, issue tracker is never for questions.

**Comment by File14** [comment]
Well, there is no other way to ask quesitons...

**Comment by ZedCee** [comment]
@File14 Sure there is. 
gitter.im/iTXTech
