### ISSUE TITLE
SynapseAPI broken in latest Nukkit

### ISSUE THREAD

**Issue by File14** [iTXTech/SynapseAPI#23]
Hello!

In the latest Nukkit the SynapseAPI is now broken. I cannot connect to my server it's just saying "Building Terrain" then after some seconds I get timeout. However if I look at the console it says that the player is logged into the server while I have the "Building Terrain" screen but once I get timeout the player disconnects from the SynapseAPI server.

UPDATE:
After looking into Nemisys console I see that everytime the player disconnects it says the server he was on was connected to Nemisys. " Client xxxx has connected successfully"

Maybe the issuse came from this? : 
https://github.com/Nukkit/Nukkit/pull/1112/commits/a71390d14980c1cd49b1e6a9b0e6109ddae31b9f
https://github.com/Nukkit/Nukkit/pull/1103/commits/f174b02b23ea42810105050730ed1e24524caf8d
https://github.com/Nukkit/Nukkit/pull/1111/commits/32d9eda90eddb22fcb733e12f2d683c5efb9abf3

**Comment by SupremeMortal** [comment]
Try the latest one from here https://ci.potestas.xyz/job/SynapseAPI/

**Comment by File14** [comment]
Alright, I'll check

**Comment by File14** [comment]
Nope, it's not fixed. Use it with latest Nukkit and it won't work for you either! ^^

**Comment by SupremeMortal** [comment]
Ok. Let me check

**Comment by SupremeMortal** [comment]
Latest version of Nemisys and Nukkit is working for me. Do you have any plugins that may be conflicting?

**Comment by File14** [comment]
No, I don't. What Nukkit build are you using?

**Comment by SupremeMortal** [comment]
Latest from here: http://ci.regularbox.com/job/Nukkit/

**Comment by File14** [comment]
I'm using that also with your SynapseAPI and latest Nemisys but its not working. hmmm

**Comment by File14** [comment]
I don't think you are using the latest Nukkit, try again. https://1432-36117051-gh.circle-artifacts.com/0/tmp/circle-artifacts.xzLHV3s/nukkit-1.0-SNAPSHOT.jar

**Comment by File14** [comment]
@SupremeMortal They reverted a commit in Nukkit that made it work again! :)

**Comment by SupremeMortal** [comment]
Yup ;)
