### ISSUE TITLE
Socket Error: Connection refused

### ISSUE THREAD

**Issue by kvetinac97** [iTXTech/SynapseAPI#3]
I put the self-compiled SynapseAPI. In config, I set up with mainServer 127.0.0.1:19132 and not mainServer as 127.0.0.1:19142. At both ports and IPs, servers are set up correctly, however, I still get this error:

Synapse Client can't connect 127.0.0.1:19142
22:19:34 [ERROR] Socket error: Connection refused

and

Synapse Client can't connect 127.0.0.1:19132
22:19:34 [ERROR] Socket error: Connection refused

**Comment by PeratX** [comment]
SPP's default port is 10305

**Comment by PeratX** [comment]
You must setup a Synapse/Nemisys server.
