### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/SynapseAPI#30]
Hello, if I join from a Genisys server about Nemisys and connect to Nukkit I'll get an Timeout error

Console LOG:

12:35:50 [INFO] JackboyPlay[/93.230.56.194:19132] logged in with entity id 10 at (world, 122.5389, 4.0, 125.4)
12:35:51 [INFO] JackboyPlay joined the game
> ppl
12:36:13 [INFO] Unknown command. Try /help for a list of commands
12:36:17 [INFO] <JackboyPlay> A
12:36:18 [NOTICE] [SynapseAPI] Synapse Client has disconnected due to timeout
12:36:18 [NOTICE] Trying to re-connect to Synapse Server
12:36:18 [NOTICE] SynapseAPI has connected to SurvivalHive.de:19132
12:36:18 [INFO] Server Closed: timeout
12:36:18 [INFO] JackboyPlay[/93.230.56.194:19132] logged out due to Server Closed: timeout
12:36:18 [NOTICE] [SynapseAPI] Connecting SurvivalHive.de:19132
12:36:18 [NOTICE] [SynapseAPI] Login success to SurvivalHive.de:19132
12:37:03 [INFO] damiboylp[/92.74.243.40:19132] logged in with entity id 11 at (world, 128.0, 4.0, 128.0)
12:37:04 [INFO] damiboylp joined the game
12:37:06 [NOTICE] Player data not found for "frankjavier", creating new profile
12:37:06 [INFO] frankjavier[/75.74.173.166:19132] logged in with entity id 12 at (world, 128.0, 4.0, 128.0)
12:37:07 [INFO] frankjavier joined the game
12:37:33 [NOTICE] [SynapseAPI] Synapse Client has disconnected due to timeout
12:37:33 [NOTICE] Trying to re-connect to Synapse Server
12:37:33 [INFO] Server Closed: timeout
12:37:33 [INFO] damiboylp[/92.74.243.40:19132] logged out due to Server Closed: timeout
12:37:33 [INFO] Server Closed: timeout
12:37:33 [INFO] frankjavier[/75.74.173.166:19132] logged out due to Server Closed: timeout
12:37:33 [NOTICE] SynapseAPI has connected to SurvivalHive.de:19132
12:37:33 [NOTICE] [SynapseAPI] Connecting SurvivalHive.de:19132
12:37:33 [NOTICE] [SynapseAPI] Login success to SurvivalHive.de:19132

**Comment by SupremeMortal** [comment]
@JackboyPlay Try using the latest version

**Comment by boybook** [comment]
See https://github.com/iTXTech/SynapseAPI/issues/19
