### ISSUE TITLE
Transfer Player

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/SynapseAPI#31]
Hello, can anyone send me the code how to transfer a **NORMAL NUKKIT PLAYER** to a server in the Nemisys network! 
Sorry that I ask it here in the issues section.

**Comment by MrLuangamerDev** [comment]
Player p = Server.getInstance().getPlayer("Test");
if (p instanceof SynapsePlayer) {
  SynapsePlayer sp = (SynapsePlayer) p;
  sp.transfer("Client Hash or Ip:port");
}

Thank you,
Luan Pereira
