### ISSUE TITLE
TCP instead of UDP

### ISSUE THREAD

**Issue by Creeperface01** [iTXTech/SynapseAPI#37]
what about TCP? wouldn't it be more stable? Now some packets get lost, so for example if player leave, synapse doesn't receive a packet sometimes. Or is that synapse/nemisys issue?

**Comment by boybook** [comment]
Synapse Proxy Protocol is already used TCP, not UDP. You can view https://github.com/iTXTech/SynapseAPI/blob/master/src/org/itxtech/synapseapi/network/synlib/SynapseSocket.java

**Comment by boybook** [comment]
I'm founding the reason of the packet loss.
I have some suggestions about this. To reduce the data transmission speed and the amount of data sent. And please make the connection to be reliable and stable, try not to trigger TCP packet loss and packet loss retransmission mechanism.

**Comment by Creeperface01** [comment]
Yes sorry i forgot to close this issue
