### ISSUE TITLE
TransferPacket

### ISSUE THREAD

**Issue by kvetinac97** [iTXTech/SynapseAPI#5]
There hasn't been any SynapseTransfer for Nukkit, so I tried to add it as a function to SynapseAPI. However, I don't know how get Synapse player UUID && what is server hash and how get it...

**Comment by boybook** [comment]
`ClientData data = SynapseAPI.getInstance().getClientData();`
Other servers' data(like hash, ip, player count) are all in ClientData.

`String serverHash = SynapseAPI.getInstance().getHash();`
`UUID uuid = player.getUUID();`

**Comment by kvetinac97** [comment]
Now, there's getClientHashByDescription method in ClientData, so I can transfer players by the SynapseTransfer PHP method
