### ISSUE TITLE
Transfer player to another client

### ISSUE THREAD

**Issue by File14** [iTXTech/SynapseAPI#9]
Hello!

How do I transfer a player to another client? Where is the API for this? 
I'm using Nukkit servers with SynapseAPI and Nemisys as a Proxy. @PeratX 

Best Regards,
File14

**Comment by kvetinac97** [comment]
I'll look for it tomorrow and make a pull request :)

**Comment by boybook** [comment]
@PeratX will write an API plugin for it, but we need to make it more stable now!

**Comment by kvetinac97** [comment]
You an use this code for moment (add to SynapseAPI):

public boolean transfer(String desc, Player player){
        String hash = clientData.getHashByDescription(desc);
        if (hash == null){
            return false;
        }
        if (desc.equals(getDescription())){
            return false;
        }
        ((SynapsePlayer) player).transfer(hash);
        return true;
    }
and then SynapseAPI.getInstance().transfer("description", player);

**Comment by File14** [comment]
Thanks, it works! However when I transfer to another server the FloatingTextParticle is still there from the previous server that I was on. Any fix?

**Comment by File14** [comment]
May I also ask if it's possible to getOnlinePlayers in an int from another client?

**Comment by Creeperface01** [comment]
use synapseApi.transferPlayer()

**Comment by DaMatrix** [comment]
Unless the code has changed drastically since @kvetinac97 's comment, you now need to add
`public boolean transfer(String desc, Player player){
String hash = clientData.getHashByDescription(desc);
if (hash == null){
return false;
}
if (desc.equals(getDescription())){
return false;
}
((SynapsePlayer) player).transfer(hash);
return true;
}`
to `SynapseEntry.java`, not SynapseAPI.

**Comment by File14** [comment]
How to transfer player now? There code is broken.

**Comment by Creeperface01** [comment]
No

**Comment by Creeperface01** [comment]
Every player is SynapsePlayer

**Comment by File14** [comment]
Tell me what code to use please. I tired your way but did not work.

**Comment by File14** [comment]
After that the code broke: https://github.com/iTXTech/SynapseAPI/commit/d274062addf3beeec541c6259ecdafbda286e4bd

**Comment by Creeperface01** [comment]
No... If you get player instance wherever, its instance of synapse player that you can use to transfer

**Comment by File14** [comment]
Yes, but how? SynapseAPI.getInstance().????

**Comment by Creeperface01** [comment]
No...

**Comment by File14** [comment]
Can you tell me?

**Comment by Creeperface01** [comment]
((SynapsePlayer)  player).someMethod()

**Comment by File14** [comment]
Thanks worked!

**Comment by File14** [comment]
I tried it now but it didn't transfer the player... and the desc is correct for the server

**Comment by Creeperface01** [comment]
You must use hash instead of description

**Comment by File14** [comment]
What is "hash"?

**Comment by Creeperface01** [comment]
Server hash search "getHashByDescription" method in API

**Comment by File14** [comment]
https://github.com/iTXTech/SynapseAPI/blob/4aed84fb3297aa1bf6ba5c56c771633c05f9044a/src/org/itxtech/synapseapi/utils/ClientData.java
It's the description?

**Comment by File14** [comment]
How do I get to know the hash for each server?

**Comment by Creeperface01** [comment]
getHashByDescription method.. Probably in ClientaData class

**Comment by File14** [comment]
Yes but I cannot do that because I just need the hash you see: org.itxtech.synapseapi.SynapsePlayer.transfer(String hash)

You can't do SynapseAPI.getInstance().getHash etc... it's not working.

**Comment by Creeperface01** [comment]
GetHashByDescription method in ClientaData you can get ClientaData from synapsePlayer

**Comment by File14** [comment]
No, i cannot. ClientData is not in SynapsePlayer.

**Comment by File14** [comment]
Okay thanks!

**Comment by tigerza117** [comment]
((SynapsePlayer) event.getPlayer()).transfer(((SynapsePlayer) event.getPlayer()).getSynapseEntry().getClientData().getHashByDescription("lobby"));

This Work

**Comment by MattWAnderson** [comment]
Can I get more information on this? Perhaps a sample code for this? of this in action somewhere? Using the code from comment on 11/11/16 in my end plugin, but how are we calling out to SynapseAPI for it to grab this info?

**Comment by MattWAnderson** [comment]
@File14
